chore: Remove high vulnerabilities (M2-8770) (#2178)
* Upgrade Node {22.21.* => 24.*.*}

* yarn upgrade

Before: 4 vulnerabilities
After: 0 vulnerabilities

* yarn upgrade --latest --pattern @typescript-eslint

Removes the following error when running ESLint:

    =============
    WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
    You may find that it works just fine, or you may not.
    SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0
    YOUR TYPESCRIPT VERSION: 5.9.3
    Please only submit bug reports when using the officially supported version.
    =============

* yarn lint:fix

Before: 352 problems (3 errors, 349 warnings)
After: 349 problems (0 errors, 349 warnings)

* Remove redundant "prettier:*" scripts

We already run Prettier with ESLint.

* Move @testing-library/* to devDependencies

* Move @types/* to devDependencies

* Move more dependencies to devDependencies

    @babel/runtime
    dotenv
    typescript
    vite-plugin-svgr

* yarn add @types/react-transition-group --dev

* yarn add @mui/system@^5.14.11

* yarn add @mui/types@~7.2.15 --dev

* Remove unused @ts-expect-error directives

    error TS2578: Unused '@ts-expect-error' directive.

* Add "lint" script alias for "lint:check"

* Simplify ci.yml to directly call `yarn lint`

We run Prettier with ESLint, so don't need to run Prettier separately.